### ISSUE TITLE
ServiceAccount labeled for env

### ISSUE THREAD

**Issue by theganyo** [apigee/apigee-remote-service-cli#153]
Our ServiceAccount is generated in the config like so:

```
kind: ServiceAccount
metadata:
  labels:
    env: test
    org: myorg
  name: apigee-remote-service-envoy
  namespace: apigee
```

I believe the ServiceAccount isn't env-specific and it's misleading when running multi-tenant. We should just remove at least the `env` label.
